# Setup 

## Setup Instructions

These steps may be skipped if the setup has already been completed.

### Step #1: Install Anaconda

Download and install the latest version of Anaconda from:
👉 https://www.anaconda.com/

The current version of Anaconda is Anaconda 3.

After installation and running Anaconda, you will get a similar environment where Jupyter and Spyder are already installed.
These are the target tools for this course.

### Step #2: Start Jupyter or Spyder for Python

You can start Jupyter or Spyder in one of the following ways:

From the Anaconda GUI (this is the most time-consuming method)

Directly from the Start Menu without opening Anaconda

### Step #3: Install Libraries / Packages in Python

During your work, you will frequently need Python libraries/packages.
The required libraries for this course are:

SkyPi

OpenCV

scikit-image

Pillow

Matplotlib

### Step #4: Install NumPy

Search for NumPy using Google.

One of the official links is:
👉 https://pypi.org/project/numpy/

Copy the installation command from the website.

Paste it into the command prompt of Jupyter or Spyder.

NumPy will be installed locally.

# Review and practice the two Python cheat sheets

[NumPy Python Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)


# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [57]:
zero_arr= np.zeros(10)
zero_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [58]:
one_arr= np.ones(10)
one_arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [59]:
five_arr= np.ones(10)*5
five_arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [60]:
arr= np.arange(10, 51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [61]:
even_arr= np.arange(10, 51, 2)
even_arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [62]:
matrix= np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [63]:
id_matrix= np.identity(3).reshape(3,3)
id_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [64]:
random_num= np.random.randn(1)
random_num

array([-1.09353075])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [65]:
arr= np.random.randn(25)
arr

array([-0.01905047,  1.37623118,  0.47368068, -0.09201464,  0.63618713,
       -0.37249177, -1.38180135, -0.07651265, -1.21896724,  0.77626055,
        0.71023405,  0.4524661 ,  0.17240293, -0.64384401,  0.87573063,
        0.31552364,  1.68005735,  0.29313248,  0.21967177,  0.5878925 ,
        0.35381681,  0.05579687,  0.29019554,  1.91964285, -0.27818438])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [66]:
arrr= np.linspace(0, 1, 20)
arrr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

### Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [67]:
import numpy as np

arr_2d = np.array([
    [5, 10, 15],
    [20, 25, 30],
    [35, 40, 45]
], np.uint8)

arr_2d


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]], dtype=uint8)

Retrieve the value 25 from the array using indexing.

In [68]:
arr_2d[1,1]

25

Extract the second row of the array.

In [69]:
arr_2d[1:2]

array([[20, 25, 30]], dtype=uint8)

Extract the third column of the array.

In [70]:
arr_2d[2:]

array([[35, 40, 45]], dtype=uint8)

Extract the bottom-right 2×2 sub-array from arr_2d.

In [71]:
arr_2d[1: , 1:]

array([[25, 30],
       [40, 45]], dtype=uint8)


# Task #2: Loading and Visualizing Images


a.	Loading/reading image using OpenCv

In [6]:
%pip install opencv-python

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [5]:
import cv2
import numpy as np
path = "cameraman.png"
img = cv2.imread(path) 
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
#Load the image data into a NumPy array
import matplotlib.pyplot as plt
plt.imshow(img)
plt.show()


error: OpenCV(5.0.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:199: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


In [53]:
print(cv2.__version__)

NameError: name 'cv2' is not defined

b.	Loading/reading image using PIL

In [3]:
from PIL import Image
img2 = Image.open('images/lena_gray_256.png') #load image into a PIL Image object

import matplotlib.pyplot as plt
import matplotlib.cm as cm
plt.imshow(img2, cmap = cm.Greys_r)
plt.show()


FileNotFoundError: [Errno 2] No such file or directory: 'images/lena_gray_256.png'

# Task #3: Image Storing

a.	Saving image to disc using OpenCV




In [37]:
cv2.imwrite('new_image.jpg', img)

True

b.	Saving image to disc using PIL

In [38]:
img2.save('new_image2.jpg')

# Task #4: Display image as an Array



In [39]:

print(img.shape) #Note: img1 loaded using open cv is a numpy array
print(img)



(256, 256, 3)
[[[156 156 156]
  [159 159 159]
  [158 158 158]
  ...
  [151 151 151]
  [152 152 152]
  [152 152 152]]

 [[160 160 160]
  [154 154 154]
  [157 157 157]
  ...
  [154 154 154]
  [155 155 155]
  [153 153 153]]

 [[156 156 156]
  [159 159 159]
  [158 158 158]
  ...
  [151 151 151]
  [152 152 152]
  [152 152 152]]

 ...

 [[114 114 114]
  [132 132 132]
  [123 123 123]
  ...
  [135 135 135]
  [137 137 137]
  [114 114 114]]

 [[121 121 121]
  [126 126 126]
  [130 130 130]
  ...
  [133 133 133]
  [130 130 130]
  [113 113 113]]

 [[121 121 121]
  [126 126 126]
  [130 130 130]
  ...
  [133 133 133]
  [130 130 130]
  [113 113 113]]]


In [40]:
import numpy as np
# Convert the image to a NumPy array
img_array = np.array(img2)


In [41]:
# Print the array
print(img_array.shape)
print(img_array)

(256, 256, 3)
[[[163 163 163]
  [161 161 161]
  [162 162 162]
  ...
  [167 167 167]
  [174 174 174]
  [155 155 155]]

 [[161 161 161]
  [161 161 161]
  [163 163 163]
  ...
  [168 168 168]
  [171 171 171]
  [152 152 152]]

 [[161 161 161]
  [163 163 163]
  [164 164 164]
  ...
  [168 168 168]
  [169 169 169]
  [158 158 158]]

 ...

 [[ 49  49  49]
  [ 57  57  57]
  [ 56  56  56]
  ...
  [ 77  77  77]
  [ 96  96  96]
  [ 89  89  89]]

 [[ 44  44  44]
  [ 53  53  53]
  [ 48  48  48]
  ...
  [ 88  88  88]
  [101 101 101]
  [ 98  98  98]]

 [[ 45  45  45]
  [ 52  52  52]
  [ 58  58  58]
  ...
  [ 99  99  99]
  [ 98  98  98]
  [105 105 105]]]


## 

# Task #5: Save your work

in the terminal, write:

```bash
git add .
git commit -m "Completed lab1 tutorial"
git push origin master
```